server:
  port: 8001
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://118.24.171.163:3306/exercise?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
    username: lgq
    password: lgq

mybatis:
  type-aliases-package: com.hand.*.domain
  mapper-locations: classpath*:com/hand/*/mapper/*.xml